### ISSUE TITLE
🐛 Crashes when clicking any control button in a meeting room for iOS<14.x

### ISSUE THREAD

**Issue by a-tokyo** [daily-co/react-native-daily-js-playground#1] opened 2021-02-23 17:01 UTC
Description:
• App fully crashes when the user presses on any control button in the meeting room. eg: Turn Camera Off, Mute, Leave meeting.

How to reproduce:
• Open the app
• Join a room
• Try to mute your mic or turn off your camera or leave the meeting using the control butons

Screenshot of error:
<img width="1405" alt="daily_rn_buggy" src="https://user-images.githubusercontent.com/12428415/108878695-328fcc00-7609-11eb-815c-36a7ff9ff248.png">

Technical details:
- iOS version: 11.4

Native logs:
```
flipper: FlipperClient::addPlugin Inspector
flipper: FlipperClient::addPlugin Preferences
flipper: FlipperClient::addPlugin React
flipper: FlipperClient::addPlugin Network
2021-02-23 18:54:09.246349+0200 DailyPlayground[40817:360594] [native] Running application DailyPlayground ({
    initialProps =     {
    };
    rootTag = 1;
})
2021-02-23 18:54:09.535730+0200 DailyPlayground[40817:360743] [] nw_connection_get_connected_socket 5 Connection has no connected handler
2021-02-23 18:54:09.536281+0200 DailyPlayground[40817:360743] TCP Conn 0x60400016e280 Failed : error 0:61 [61]
2021-02-23 18:54:09.626563+0200 DailyPlayground[40817:360758] [javascript] YellowBox has been replaced with LogBox. Please call LogBox.ignoreLogs() instead.
2021-02-23 18:54:09.690508+0200 DailyPlayground[40817:360758] [javascript] Running "DailyPlayground" with {"rootTag":1,"initialProps":{}}
2021-02-23 18:54:12.034876+0200 DailyPlayground[40817:360594] [MC] System group container for systemgroup.com.apple.configurationprofiles path is /Users/Tokyo/Library/Developer/CoreSimulator/Devices/F19CFEC8-4AF2-48B4-8729-2C0CFB79205C/data/Containers/Shared/SystemGroup/systemgroup.com.apple.configurationprofiles
2021-02-23 18:54:12.035278+0200 DailyPlayground[40817:360594] [MC] Reading from private effective user settings.
2021-02-23 18:54:31.591532+0200 DailyPlayground[40817:360741] Error loading /Library/Audio/Plug-Ins/HAL/BartenderAudioPlugIn.plugin/Contents/MacOS/BartenderAudioPlugIn:  dlopen(/Library/Audio/Plug-Ins/HAL/BartenderAudioPlugIn.plugin/Contents/MacOS/BartenderAudioPlugIn, 262): no suitable image found.  Did find:
	/Library/Audio/Plug-Ins/HAL/BartenderAudioPlugIn.plugin/Contents/MacOS/BartenderAudioPlugIn: mach-o, but not built for iOS simulator
2021-02-23 18:54:31.591755+0200 DailyPlayground[40817:360741] Cannot find function pointer New_SHP_PlugIn for factory <CFUUID 0x60800022d1a0> 834FC054-C1CC-11D6-BD01-00039315CD46 in CFBundle/CFPlugIn 0x7ff45a634210 </Library/Audio/Plug-Ins/HAL/BartenderAudioPlugIn.plugin> (bundle, not loaded)
2021-02-23 18:54:31.911338+0200 DailyPlayground[40817:360758] [javascript] could not check for username in localStorage
2021-02-23 18:54:32.537035+0200 DailyPlayground[40817:360758] [javascript] logging and telemetry enabled
2021-02-23 18:54:32.538595+0200 DailyPlayground[40817:360758] [javascript] = Calculate Load Times: performance NOT supported
2021-02-23 18:54:32.538904+0200 DailyPlayground[40817:360758] [javascript] initializing callstats
2021-02-23 18:54:32.541909+0200 DailyPlayground[40817:360758] [javascript] 'subscribing to all tracks', null
2021-02-23 18:54:32.547240+0200 DailyPlayground[40817:360758] [javascript] 'getUserMedia called with constraints: {"audio":{},"video":{"width":640,"height":480}}.', null
2021-02-23 18:54:32.559032+0200 DailyPlayground[40817:360758] [javascript] '[daily.co event]', 'participant-updated'
2021-02-23 18:54:32.564699+0200 DailyPlayground[40817:360758] [javascript] '[daily.co event]', 'participant-updated'
2021-02-23 18:54:32.566937+0200 DailyPlayground[40817:360758] [javascript] 'joining session', null
2021-02-23 18:54:32.568990+0200 DailyPlayground[40817:360594] [native] SocketRocket: In debug mode.  Allowing connection to any root cert
2021-02-23 18:54:33.384191+0200 DailyPlayground[40817:360758] [javascript] 'rtc joined meeting', 'plural-test/test'
2021-02-23 18:54:33.385580+0200 DailyPlayground[40817:360758] [javascript] connected to signaling server
2021-02-23 18:54:33.385951+0200 DailyPlayground[40817:360758] [javascript] '  room:', 'plural-test/test'
2021-02-23 18:54:33.386271+0200 DailyPlayground[40817:360758] [javascript] '  participant id:', '81a62c78-1067-4d5f-bb97-1061e4c68336'
2021-02-23 18:54:33.388780+0200 DailyPlayground[40817:360758] [javascript] '[daily.co event]', 'joined-meeting'
2021-02-23 18:54:33.939876+0200 DailyPlayground[40817:360758] [javascript] 'fetching stun info from twilio', null
2021-02-23 18:54:36.914979+0200 DailyPlayground[40817:361321] [AudioHAL_Client] HALB_IOBufferManager.cpp:226:GetIOBuffer:  HALB_IOBufferManager::GetIOBuffer: the stream index is out of range
2021-02-23 18:54:36.915169+0200 DailyPlayground[40817:361321] [AudioHAL_Client] HALB_IOBufferManager.cpp:226:GetIOBuffer:  HALB_IOBufferManager::GetIOBuffer: the stream index is out of range
2021-02-23 18:54:36.927403+0200 DailyPlayground[40817:361321] [aqme] 254: AQDefaultDevice (1): output stream 0: null buffer
2021-02-23 18:54:36.927677+0200 DailyPlayground[40817:361321] [aqme] 1433: EXCEPTION thrown (-50): -
2021-02-23 18:54:43.403082+0200 DailyPlayground[40817:360758] [javascript] session id: 97056b0b-90c9-4245-89e4-f9e8b9b5a48c
2021-02-23 18:54:45.195138+0200 DailyPlayground[40817:361143] RPCTimeout.cpp:55:_ReportRPCTimeout: GetVoiceProperty: Mach message timeout. Apparently deadlocked. Aborting now.
CoreSimulator 732.18.6 - Device: iPhone X (FXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXC) - Runtime: iOS 11.4 (15F79) - DeviceType: iPhone X
(lldb) 
```

**Comment by A-Tokyo** [comment] 2021-03-22 21:42
Update: The error doesn't occur on `iOS>=14`

But we need to fix this error for older iOS versions since most of  the users will NOT keep their iOS up to date.

**Comment by filipi87** [comment] 2022-03-08 13:41
Hi @A-Tokyo 

Only some questions that can help us to investigate:
- What is the version of `react-native-daily-js-playground` that you are using ? 
- Have you been able to test on a physical device as well or only on the simulator ?
- Are you using the Mac M1 ?

Thank you for your help!

**Comment by A-Tokyo** [comment] 2022-03-08 15:19
Hi @filipi87!

I abandoned this and used react native web view to render daily in react native.

However, I recall that the solution to this problem was related to bumping up min ios sdk ( : 

Hope this helps.

**Comment by filipi87** [comment] 2022-03-08 18:46
Hi @A-Tokyo . 

I will try to reproduce, see if It is still happening the bug, a lot of changes since you have reported.

Thanks a lot for your help!

**Comment by A-Tokyo** [comment] 2022-03-08 23:09
My pleasure! @filipi87

**Comment by filipi87** [comment] 2023-07-17 17:52
We have been able to simulate this issue here, and based on the logs, we found that this is actually a known issue on the iOS simulator. More info can be found here:
https://developer.apple.com/forums/thread/667921

Based on this, we are closing this issue, and recommend to use the latest version of the iOS when running on a simulator.

Let me know if you need any other help.

**Closed by filipi87** 2023-07-17 17:52 UTC
